### ISSUE TITLE
Touch Gestures Installer won't work

### ISSUE THREAD

**Issue by gushiikoi** [Mrcubix/Touch-Gestures#15]
everytime i try to install and click apply, my console would always say:

"[Plugin:Error]  Object construction has thrown an error
[MissingMethodException:Error]  Method not found: 'Void OpenTabletDriver.Plugin.Log.Write(System.String, System.String, OpenTabletDriver.Plugin.LogLevel)'.
   at TouchGestures.Installer.TouchGesturesInstaller..ctor()
[Tool:Error]    Failed to initialize Touch Gestures Installer tool."

so everytime i restart the touch gesture is just not there at all in the filters tab

**Comment by Mrcubix** [comment]
The exception is about the Touch Gestures Installer, and it is **very** odd that you're getting an exception at all.

Also the installer extract the plugin to the appropriate folder, provided you have OTD.EnhancedOuputMode installed as indicated in the install guide, you should be able to install it.

Didn't had issues with it on a stock windows install, my own PC, The raspberry pi sitting in my bedroom & a linux install.

Will provide an installer build that may let me know more about the issue, but i'll also provide you the actual plugin that you will have to install manually (should be done today)

**Comment by Mrcubix** [comment]
Nvm, the issue you seems to be having is due to using the installer for the wrong version of OpenTabletDriver.

Where did you download the installer from?

You may extract this in `OTD.EnhancedOutputMode`'s plugin folder manually.
[Touch-Gestures-0.6.x.zip](https://github.com/user-attachments/files/17718799/Touch-Gestures-0.6.x.zip)

**Comment by gushiikoi** [comment]
The issue I was having was that I installed the wrong version of it I think. However, I have a new issue where touch does not work at all. To begin with, touch did not work even before I opened up about the issue I was having. But I thought it would be fixed once I installed touch gestures. It did not and now I don't have touch. For context I have a CTH-470

**Comment by Mrcubix** [comment]
https://mrcubix.github.io/Touch-Gestures-Doc/installation_guide/ follow this from the dependencies install, to he end.
