### ISSUE TITLE
Installation guide is not clear about which OpenTabletDriver location it refers to

### ISSUE THREAD

**Issue by ianbdehaan** [Mrcubix/Touch-Gestures#17]
In the step "2. Extract the downloaded archive in the same location as OpenTabletDriver" of the interface installation guide it's not clear what it is meant by the same location as OpenTabletDriver, at least when it comes to linux systems. I'm aware of the locations ~/.config/OpenTabletDriver and /usr/lib/opentabletdriver, I tried using both locations to no success.

**Comment by Mrcubix** [comment]
If it's the UX, any locations realisrocally, it's just a binary that connect to OpenTabletDriver via RPC

**Comment by ianbdehaan** [comment]
I guess I have some other problem then, I assumed it only due to the file location, but it never connects:
![image](https://github.com/user-attachments/assets/6e28eb46-6fb8-4bd0-93e0-0798d6ebcf4a)
any idea on how to debug it?

**Comment by ianbdehaan** [comment]
all is enabled. here follows the diagnostics:
[otd_diagnostics.json](https://github.com/user-attachments/files/17923167/otd_diagnostics.json)

**Comment by Mrcubix** [comment]
Restart the daemon

**Comment by ianbdehaan** [comment]
sorry, I repeated the process a few times, think last time I forgot to restart. This however doesn't solve the problem... New diagnostics file:
[otd_diagnostics2.json](https://github.com/user-attachments/files/17923326/otd_diagnostics2.json)

**Comment by Mrcubix** [comment]
![image](https://github.com/user-attachments/assets/40414b24-bb0a-4981-83cb-6c39d3f9f791)

**Extremely** odd

![image](https://github.com/user-attachments/assets/1d926d4b-7c26-4bb9-acbd-e148ce4eb61f)

Also i do not see a restart.

You may check the plugin folder at `.config/OpenTabletDriver/Plugins/OTD.EnhancedOutputMode` to see if the following dlls are there:

![image](https://github.com/user-attachments/assets/b0935ce4-7be4-41ad-80c4-519d7fda2e40)

**Comment by ianbdehaan** [comment]
Maybe I'm performing the restart the wrong way, but currently doing "systemctl --user stop --now opentabletdriver.service" followed by "systemctl --user start --now opentabletdriver.service".

Regarding the files they are all there:
![image](https://github.com/user-attachments/assets/0467c498-f09c-45bd-afd8-6bffa2dbc185)

**Comment by Mrcubix** [comment]
> Also the touch and enhanced modes are working fine if this is relevant info.

I assume that you have enabled `Touch Settings` too, so that's out of the equation, but anyway, `Touch-Gestures.Lib.dll` not loading is definitely the issue here somehow.

**Comment by ianbdehaan** [comment]
Hi I'm trying to install it... the drag and drop method bugs for me for some reason, so I created a folder under plugins and put the file there, I'm probably doing something wrong as I'm getting this error:

![image](https://github.com/user-attachments/assets/5d3e86d9-0304-4347-a41f-d20e7de186b6)

**Comment by Mrcubix** [comment]
Huh, that's probably not good, off that i didn't encounter that, lemme provide you the artifact instead
https://github.com/Mrcubix/Touch-Gestures/actions/runs/11599839489#:~:text=Produced%20during%20runtime-,Name,-Size

**Comment by ianbdehaan** [comment]
sorry... this is starting to prove to be too hard, thought it was only a file placement issue, I'm in a busy period so I'll have to leave it for now, thanks a lot for trying to help though!

**Comment by Mrcubix** [comment]
Sorry, it is easy in most cases, except cases where the core plugin loading breaks for no good reasons 
(which i can't replicate on 2 machines so far, but i never tried using Arch so who knows, could be an issue there).

Also, it turns out there was an issue with the installer, since i figured out an MSBuild hack to not have to dupe projects.

New Beta Release: https://github.com/Mrcubix/Touch-Gestures/releases/tag/1.1.0-beta2

Take a loot at the `Update Troubleshooting` section of the release containing the steps to take before attempting to update (follow the same installation steps for the install after doing so)

**Comment by Mrcubix** [comment]
Got around to setting up an arch VM using the broken installer.
I'm still unable to replicate the issue, so most likely user error on your part.
Brought some clarification to the documentation.

https://github.com/user-attachments/assets/715de34b-5853-4b6b-866f-d43ef5d0cc85
