### ISSUE TITLE
Doesnt connect to daemon / Connecting.....

### ISSUE THREAD

**Issue by OhKayBet** [Mrcubix/Touch-Gestures#7]
Arch Linux
OTD

Filters : 
Touch Settings: Enabled
Touch Gestures: Enabled

Tools:
Touch Gestures Installer: Enabled
     Force Install: Disabled
Touch Gestures Daemon: Enabled

systemctl --user status opentabletdriver.service 
enabled & started
Loading plugin 'Touch Gestures Installer'

pacman -Q
dotnet-runtime 8.0.7.sdk107-1
dotnet-sdk 8.0.7.sdk107-1

UX Installed linux x64

**Comment by Mrcubix** [comment]
Would you mind uploading a diag file from OTD, as well as the app log when launched from the console?

**Comment by OhKayBet** [comment]
Hello, I just restarted my pc and its connecting. I believe that it maybe it was due to me updating my system that involved a kernel update. likely it was trying to connect to the updated kernel but since i was still running on an older version it wasnt connecting to the daemon. would explain why opentabletdriver gui was connecting but not the touch gestures. Maybe?

**Comment by Mrcubix** [comment]
Let me know in another issue with the specifics as i have a bit of a hard time understanding what you mean (i'm a very visual person so i might need images of the interface itself)

**Comment by OhKayBet** [comment]
> Let me know in another issue with the specifics as i have a bit of a hard time understanding what you mean (i'm a very visual person so i might need images of the interface itself)

all good, had to uninstall and reinstall everything.
